// SEMI-AUTO-GENERATED by tools/gen_maps.py
// 골격(타일/워프)은 자동 생성, NPC/대사/트리거/추가 맵(MAP_RIVAL_HOUSE 등)은 손편집 영역.
// 재생성 시 손편집된 데이터가 사라집니다 — git diff로 복원 필요.
#pragma once
#include "sprites.h"  // NPC_SPR_* enum 사용

// ─── 타일 종류 ─────────────────────────────────────────────────
// ' '  빈 땅/잔디 (이동 가능)
// '.'  길 (이동 가능)
// ';'  긴 풀 (야생 인카운터)
// '#'  벽/건물/나무 (통과 불가)
// '~'  물 (통과 불가, 비주얼)
// 'D'  문 (워프 타일)
// 's'  표지판
// 'N'  NPC 위치

// NpcDef.spriteId / TrainerDef.spriteId 는 sprites.h의 NpcSpriteId enum 인덱스.
//   0 MOM   1 OAK   2 BLUE        3 GRAMPS    4 NURSE    5 CLERK
//   6 GIRL  7 BRUNETTE   8 LITTLE_BOY  9 LITTLE_GIRL  10 FISHER
//   11 GENTLEMAN   12 POKE_BALL
// NpcDef.trigger: 대화 종료 시 emit할 이벤트
//   0 = 없음, 1 = STARTER_TRIGGER (연구소 오박사 → 스타터 선택, partySize==0일 때만)
//   2 = NURSE_HEAL  3 = 마트 소포 수령(gotParcel 설정)
// NpcDef.tag: 조건부 동작/표시 NPC 식별자
enum NpcTag {
    NPC_TAG_NONE           = 0,
    NPC_TAG_OAK_LAB        = 1, // 연구소 오박사 (소포 퀘스트 처리)
    NPC_TAG_BLUE_LAB       = 2, // 연구소 블루 (beatenRival1 후 대사 변경 → 사라짐)
    NPC_TAG_BALL_BULBASAUR = 3, // 이상해씨 몬스터볼 (선택 시 숨김)
    NPC_TAG_BALL_CHARMANDER= 4, // 파이리 몬스터볼
    NPC_TAG_BALL_SQUIRTLE  = 5, // 꼬부기 몬스터볼
    NPC_TAG_VIRIDIAN_CLERK = 6, // 상록 마트 점원 (gotParcel 후 대사 변경)
    NPC_TAG_ITEMBALL_POTION   = 7, // 필드 포켓볼 → 상처약 1개 (획득 후 숨김)
    NPC_TAG_ITEMBALL_POKEBALL = 8, // 필드 포켓볼 → 몬스터볼 1개 (획득 후 숨김)
    NPC_TAG_ITEMBALL_CANDY    = 9, // 필드 포켓볼 → 이상한사탕 1개 (획득 후 숨김)
};
struct NpcDef {
    int x, y;
    const wchar_t* lines[4];
    int spriteId = 0;
    int trigger  = 0;
    int tag      = 0;
    int martId   = 0;  // >0 이면 대화 후 상점 진입 (player.h::MartId)
};

struct TrainerDef {
    int x, y;
    int dir;
    int sightRange;
    const wchar_t* name;
    const wchar_t* preBattleText;
    int partyIds[3];
    int partyLevels[3];
    bool defeated;
    int spriteId = 11;       // OW 모양 — 기본 GENTLEMAN
    int introSpriteId = 0;   // 배틀 시작 시 풀바디 IntroSprite (0=OAK, 1=RIVAL, ...)
    bool isBoss = false;     // 체육관 관장(브록 등) 표시 — BOSS_BATTLE 트리거
    int prize = 0;           // 격파 시 상금 ($). 0이면 기본값(일반 100, isBoss 1000)
};

struct WarpDef {
    int srcX, srcY;
    int destMap;
    int destX, destY;
};

struct EncounterEntry {
    int speciesId;
    int minLevel, maxLevel;
    int weight;
};

struct MapDef {
    int         id;
    int         mapW, mapH;   // 실제 맵 크기 (스텝 단위)
    const char* name;
    const wchar_t* nameW;
    const char* tiles[73];   // 최대 72행 + nullptr 지원
    NpcDef      npcs[8];
    int         numNpcs;
    TrainerDef  trainers[4];
    int         numTrainers;
    WarpDef     warps[12];
    int         numWarps;
    EncounterEntry encounters[6];
    int         numEncounters;
    int         northMap;
    int         southMap;
    int         northEntryX, northEntryY;
    int         southEntryX, southEntryY;
    const wchar_t* bgmFile;
};

static const int MAP_PALLET = 0;
static const int MAP_ROUTE1 = 1;
static const int MAP_VIRIDIAN = 2;
static const int MAP_ROUTE2 = 3;
static const int MAP_VIR_FOREST = 4;
static const int MAP_PEWTER = 5;
static const int MAP_OAK_LAB = 6;
static const int MAP_PLAYER_HOUSE = 7;
static const int MAP_PEWTER_GYM = 8;
static const int MAP_PLAYER_HOUSE2 = 9;
static const int MAP_RIVAL_HOUSE   = 10;
static const int MAP_VIRIDIAN_PC   = 11;
static const int MAP_PEWTER_PC     = 12;
static const int MAP_VIRIDIAN_MART = 13;
static const int MAP_PEWTER_MART   = 14;
static const int MAP_ROUTE2_GATE   = 15;
static const int MAP_FOREST_NORTH_GATE = 16;
static const int MAP_FOREST_SOUTH_GATE = 17;
static const int MAP_VIRIDIAN_SCHOOL_HOUSE   = 18;
static const int MAP_VIRIDIAN_NICKNAME_HOUSE = 19;

// 실내 맵 ID — 맵 외곽 영역을 풀밭 대신 검정으로 렌더링
inline bool isIndoorMap(int id) {
    return id == MAP_OAK_LAB || id == MAP_PLAYER_HOUSE ||
           id == MAP_PLAYER_HOUSE2 || id == MAP_PEWTER_GYM ||
           id == MAP_RIVAL_HOUSE ||
           id == MAP_VIRIDIAN_PC || id == MAP_PEWTER_PC ||
           id == MAP_VIRIDIAN_MART || id == MAP_PEWTER_MART ||
           id == MAP_ROUTE2_GATE ||
           id == MAP_FOREST_NORTH_GATE || id == MAP_FOREST_SOUTH_GATE ||
           id == MAP_VIRIDIAN_SCHOOL_HOUSE || id == MAP_VIRIDIAN_NICKNAME_HOUSE;
}

// ─── Pallet Town (20×18) — pokered PalletTown.blk 원본 ─────────
inline MapDef MAP_0 = {
    MAP_PALLET, 20, 18,
    "Pallet Town", L"팔레트시티",
    {
        // gen_overworld_tiles_v3.py 자동 생성
        "!!!)!!!!!);;)!!!!!)!",
        "))))))))));;))))))))",
        ")!(&(&(&(&(&(&(&(&!)",
        ")!&(V>>W&(&(V>>W&(!)",
        ")!%%kHlm(&%%kHlm(&!)",
        ")!%=nD:o&(%=nD:o&(!)",
        ")!(&(&(&(&(&(&(&(&!)",
        ")!&(&(&(&(&(&(&(&(!)",
        ")!(&%%%%(&b2222c(&!)",
        ")!&(///=&(d3333e&(!)",
        ")!(&++++(&f^LpNu(&!)",
        ")!&(----&(g:D::P&(!)",
        ")!(&(&(&(&%%%%%%%%!)",
        ")!&(&(&(&(///=//%%!)",
        ")!!!qXXr%%++++!!%%!)",
        ")!!!Y99Z%%----!!%%!)",
        ")!!!Y99Z%%%%%%%%%%!)",
        "))!!Y99Z))))))))))))",
        nullptr
    },
    {
        // pokered PALLETTOWN_GIRL (3, 8) — _PalletTownGirlText
        // (8, 5) Oak 정적 NPC는 제거 — 원본에서도 OAK_INTERCEPT 이벤트로만 등장
        {3, 8, {
            L"소녀: 저도 포켓몬을 기르고 있어요!",
            L"소녀: 강하게 키우면 저를 지켜줄 거예요!",
            nullptr
        }, NPC_SPR_GIRL},

        // pokered PALLETTOWN_FISHER (11, 14) — _PalletTownFisherText
        {11, 14, {
            L"낚시꾼: 기술은 정말 대단해!",
            L"낚시꾼: PC로 도구와 포켓몬을 데이터로 저장하고 꺼낼 수 있다니까!",
            nullptr
        }, NPC_SPR_FISHER},
    }, 2,  // npcs
    {}, 0,  // trainers
    {
        // pokered PalletTown.asm 원본 위치
        {5, 5, MAP_PLAYER_HOUSE, -1, -1},
        {13, 5, MAP_RIVAL_HOUSE, -1, -1},
        {12, 11, MAP_OAK_LAB, -1, -1},
    }, 3,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE1, -1,  // north/south
    0, 17, 0, 0,  // entry points (north offset=0: PalletTown↔Route1 same width)
    nullptr  // bgm
};

// ─── Route 1 (20×36) ─────────────────────────────────────
inline MapDef MAP_1 = {
    MAP_ROUTE1, 20, 36,
    "Route 1", L"1번도로",
    {
        // gen_overworld_tiles_v3.py 자동 생성
        "!!!)!!!!!)%%)!!!!!)!",
        "!!!)))))))%%)))))))!",
        "!!!)!!!!!!%%!!!!++)!",
        "!!!)!!!!!!%%!!!!--)!",
        "!!!)!!!!!$%%%%%%%%)!",
        "!!!)0000<$5656%%%%)!",
        "!!!$++++!$;;;;;;;;$!",
        "!!!$----!$;;;;;;;;$!",
        "!!!$!!!!!$;;;;;;;;$!",
        "!!!$0000<$;;;;;;;;$!",
        "!!!$!!++++!!%%%%%%$!",
        "!!!$!!----!!%%%%%%$!",
        "!!!$!!!!!!!!(&;;;;$!",
        "!!!$$$0000$$$$;;;;$!",
        "!!!)!!!!++++%%;;;;)!",
        "!!!)!!!!----%%;;;;)!",
        "!!!)!!%%%%%%%%++++)!",
        "!!!)!!%%%%%%%%----)!",
        "!!!)!!%%!!!!!!!!!!)!",
        "!!!)<?56<?00000000)!",
        "!!!)!!%%%%%%%%%%%%)!",
        "!!!)!!%%%%%%%%%%%%)!",
        "!!!)!!!!!!!!;;;;%%)!",
        "!!!)$$$$$$$$;;;;56)!",
        "!!!)!!!!++++;;;;%%)!",
        "!!!)!!!!----;;;;%%)!",
        "!!!)%%%%%%%%%%%%%%)!",
        "!!!)56%%%=56565656)!",
        "!!!$!!;;;;%%!!;;;;$!",
        "!!!$!!;;;;%%!!;;;;$!",
        "!!!$;;;;++%%;;;;++$!",
        "!!!$;;;;--%%;;;;--$!",
        "!!!$))))));;))))))$!",
        "!!!$!!!!!);;)!!!!!$!",
        "!!!$!!!!!);;)!!!!!$!",
        "!!!$!!!!!);;)!!!!!$!",
        nullptr
    },
    {
        // pokered ROUTE1_YOUNGSTER1 (5, 24) — _Route1Youngster1MartSampleText
        // 원본은 포션 샘플 지급, 클론은 대사만 매핑
        {5, 24, {
            L"소년: 안녕! 나는 포켓몬마트에서 일해.",
            L"소년: 상록시티에 있으니까 꼭 들러줘!",
            L"소년: 자, 샘플로 이거 가져가!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},

        // pokered ROUTE1_YOUNGSTER2 (15, 13) — _Route1Youngster2Text (절벽 점프 팁)
        {15, 13, {
            L"소년: 길가의 절벽들이 보이지?",
            L"소년: 좀 무섭지만 점프해서 내려갈 수 있어.",
            L"소년: 팔레트로 빨리 돌아가는 지름길이지!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},
    }, 2,  // npcs
    {}, 0,  // trainers
    {}, 0,  // warps
    {
        {19, 2, 4, 50},
        {16, 2, 4, 50},
    }, 2,  // encounters
    MAP_VIRIDIAN, MAP_PALLET,  // north/south
    10, 35, 0, 0,  // entry points (north +10: Route1→Viridian offset; south 0: Route1↔Pallet same width)
    nullptr  // bgm
};

// ─── Viridian City (40×36) ─────────────────────────────────────
inline MapDef MAP_2 = {
    MAP_VIRIDIAN, 40, 36,
    "Viridian City", L"상록시티",
    {
        // gen_overworld_tiles_v3.py 자동 생성
        "*****1$$$$$$$$$$/&%%$$$$$$$$$$$$$$$$$$$$",
        "*****1$$$$$$$$$$/&%=$$$$$$$$$$$$$$$$$$$$",
        "*****1$$$$$$$$$$/&(&$$$$%%%%%%%%%%%%$$$$",
        "*****1$$$$$$$$$$/&&($$$$%%%%%%%%%%%%$$$$",
        "*****1!!!!!!!!T!(&(&(&%%%%%%b2222c%%$$$$",
        "*****1!!))))))$$&(&(&(%%%%%%d3333e%%$$$$",
        "*****1!)$$$$$$$$/&(&/&%%%%%%f^st^S%%$$$$",
        "*****1!)$$$$$$$$/&&(/&%%%%%=g:::GP%%$$$$",
        "*****1!)$$$$$$$$/&(&V>>W%%%%!!!!!!%%$$$$",
        "*****1!)$$$$$$$$/&&(_D:`565600000056$$$$",
        "*****1!)$$$$$$$$/&(&(&(&(&(&(&(&(&%%$$$$",
        "*****1!)$$$$$$$$/&&(&(&(&(&(&(&(&(%%$$$$",
        "*****1!)$$$$$$$$/&(&%%%%%%%%%%%%%%%%$$$$",
        "77777a!)$$$$$$$$/&&(////////////////$$$$",
        "!!!1!!!)$$$$$$$$/&(&V>>W(&(&(&(&(&(&$$$$",
        "!!!1!!!)$$$$$$$$/&&(_D:`&(&(&(&(&(&($$$$",
        "!!!1&(!!$$$$$$$$%%(&%%%%(&!!J22K!!(&$$$$",
        "!!!1&(!!!!!!!!!!%=&(////&(!!Q33U!!&($$$$",
        "888h(&(&(&(&(&(&(&(&++++(&!!BNNE!!(&$$$$",
        "***1&(&(&(&(&(&(&(&(----&(!!FMRI!!&($$$$",
        "***1(&!!!!!!!!!!(&(&(&(&(&(&(&(&(&(&$$$$",
        "***1$$$$!!!!!!!!&(&(&(&(&(&(&(&(&(&($$$$",
        "***1(&!!T!++++!!(&++(&J22K(&++!!!!(&$$$$",
        "***1&(!!$$----!!&(--&(Q33U&(--!!!!&($$$$",
        "***1(&!!qXXXXr!!(&!!(&BNNE(&!!!!++(&$$$$",
        "***1&(!!Y9999Z!!&(!!&(FCOI&(!!!!--&($$$$",
        "***1%%!!Y9999Z!!%%!!%%%%%%%%%%%%%%%%$$$$",
        "777a5600Y9999Z<?56<?5656565656565656$$$$",
        "!!!)(&++!!!!!!!!(&!!%%!!++++(&++++(&$$$$",
        "!!!)&(--!!!!!!!!&(!!%=!!----&(----&($$$$",
        "!!!)%%%%%%%%%%%%%%%%(&%%%%%%%%%%%%%%$$$$",
        "!!!)////////////////&(//////////////$$$$",
        "!!!!!!!!!!!!!)!!!!!)(&)!!!!!)!!!!!!!!!!!",
        "!!!!!!!!!!!!!)!!!!!)&()!!!!!)!!!!!!!!!!!",
        "!!!!!!!!!!!!!)!!!!!)(&)!!!!!)!!!!!!!!!!!",
        "!!!!!!!!!!!!!)!!!!!)&()!!!!!)!!!!!!!!!!!",
        nullptr
    },
    {
        // 서쪽 22번도로 입구 차단 노인 — 공사중 안내 (게임 스코프 한정용 커스텀 NPC)
        {5, 17, {
            L"할아버지: 으흠... 22번도로는 지금 공사중이라네.",
            L"할아버지: 미안하지만 지금은 들어갈 수 없어.",
            L"할아버지: 공사가 끝나면 다시 와주게.",
            nullptr
        }, NPC_SPR_GRAMPS},

        // pokered YOUNGSTER1 (13, 20) — _ViridianCityYoungster1Text
        {13, 20, {
            L"소년: 어이! 허리에 차고 있는 그 몬스터볼!",
            L"소년: 너 포켓몬을 가지고 있구나!",
            L"소년: 언제 어디서나 포켓몬을 데리고 다닐 수 있다니 멋지지!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},

        // pokered GAMBLER1 (30, 8) — _ViridianCityGambler1GymAlwaysClosedText
        // SPRITE_GAMBLER = 노인 → NPC_SPR_GRAMPS
        {30, 8, {
            L"할아버지: 이 포켓몬 체육관은 항상 닫혀있어.",
            L"할아버지: 도대체 관장이 누구일까?",
            nullptr
        }, NPC_SPR_GRAMPS},

        // pokered YOUNGSTER2 (30, 25) — _ViridianCityYoungster2YouWantToKnowAboutText
        {30, 25, {
            L"소년: 쐐기벌레 포켓몬 2종류에 대해 알고 싶니?",
            L"소년: 캐터피는 독이 없지만, 뿔충이는 독이 있어.",
            L"소년: 뿔충이의 독침붕 공격을 조심해!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},

        // pokered GIRL (17, 9) — _ViridianCityGirlHasntHadHisCoffeeYetText
        {17, 9, {
            L"소녀: 앗, 할아버지! 너무 그러지 마세요!",
            L"소녀: 할아버지는 아직 커피도 못 드셨거든요.",
            nullptr
        }, NPC_SPR_LITTLE_GIRL},

        // pokered OLD_MAN_SLEEPY (18, 9) — _ViridianCityOldManSleepyPrivatePropertyText
        // SPRITE_GAMBLER_ASLEEP — NPC_SPR_GRAMPS 유지
        {18, 9, {
            L"할아버지: 이쪽으로는 지나갈 수 없다!",
            L"할아버지: 여기는 사유지란 말이다!",
            nullptr
        }, NPC_SPR_GRAMPS},

        // pokered FISHER (6, 23) — ViridianCityFisherYouCanHaveThisText (드림이터 TM)
        {6, 23, {
            L"낚시꾼: 하암~! 햇볕에 깜빡 졸았네. 슬리프가 꿈을 먹는 꿈을 꿨어.",
            L"낚시꾼: 어라? 이 비전머신은 어디서 났지?",
            L"낚시꾼: 왠지 으스스하군... 자, 너 가져라!",
            nullptr
        }, NPC_SPR_FISHER},
    }, 7,  // npcs
    {}, 0,  // trainers
    {
        {23, 25, MAP_VIRIDIAN_PC, 3, 7},
        {29, 19, MAP_VIRIDIAN_MART, 3, 7},
        // 학교(트레이너 팁) 하우스 — pokered ViridianSchoolHouse
        {21, 15, MAP_VIRIDIAN_SCHOOL_HOUSE, 3, 7},
        // 별명짓기 하우스 — pokered ViridianNicknameHouse
        {21, 9, MAP_VIRIDIAN_NICKNAME_HOUSE, 3, 7},
        // 상록시티 체육관 — pokered: 8뱃지 모을 때까지 잠겨있음. destMap=-1 → "문이 잠겨있다..."
        {32, 7, -1  /*VIRIDIAN_GYM (locked)*/, -1, -1},
    }, 5,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE2, MAP_ROUTE1,  // north/south
    -10, 35, -10, 0,  // entry points (north -10: Viridian→Route2; south -10: Viridian→Route1)
    nullptr  // bgm
};

// ─── Route 2 (20×36) ─────────────────────────────────────
inline MapDef MAP_3 = {
    MAP_ROUTE2, 20, 72,
    "Route 2", L"2번도로",
    {
        // gen_overworld_tiles_v3.py 자동 생성
        "$$$$$$$$(&$$$$$$$$$$",
        "$$$$$$$$&($$$$$$$$$$",
        ";;;;;;;;(&/&%%%%%%%%",
        ";;;;;;;;&(/&%%%%%%%%",
        ";;;;;;;;(&/&%%%%%%%%",
        ";;;;;;;;&(/&%%%%%%%%",
        ";;;;;;;;(&i888888h%%",
        ";;;;;;;;&(A******1%%",
        "%%%%%%%%%%A******1%%",
        "%%%%%%%%%%j7v7777a%%",
        "$$$!$T$$$$%%%%++++!!",
        "!!$!$!!!!!%=%%----!!",
        "!!J22K!!!!%%%%%%%%%%",
        "!!Q33U!!!!%%%%%%%%%%",
        "!!BNNE!!!!!!!!!!!!%%",
        "))FD@I))))))))!!!!%%",
        "44444444$$$$$$!!!!%%",
        "44444444$$$$$$!!!!%%",
        "%%%%%%%%$$$$$$V>>W%%",
        "56565656$$$$$$_D:`%%",
        ";;(&;;;;$$$$$$%%%%%%",
        ";;&(;;;;$$$$$$%%%%%%",
        "$$$$$$$$$$$$$$$T$$$$",
        "$$$$$$$$$$$$$$$!!!!!",
        "$$$$$$$$$$$$$$!!!!!!",
        "$$$$$$$$$$$$$$!!!!!!",
        "$$$$$$$$$$$$$$!!!!!!",
        "$$$$$$$$$$$$$$00<?00",
        "$$$$$$$$$$$$$$!!!!++",
        "$$$$$$$$$$$$$$!!!!--",
        "$$$$$$$$$$$$$$!!!!!!",
        "$$$$$$$$$$$$$$00<?00",
        "$$$$$$$$$$$$$$!!!!++",
        "$$$$$$$$$$$$$$!!!!--",
        "$$$$$$$$$$$$$$!!!!!!",
        "$$$$$$$$$$$$$$))!!))",
        "$$$$$$$$$$$$$$J2222K",
        "$$$$$$$$$$$$$$Q3333U",
        "$$$!$T$$$$$$$$BNNNNE",
        "!!$!$!!!!!$$$$FD@@@I",
        "!!J22K!!!!$$$$!!!!!!",
        "!!Q33U!!!!$$$$!!!!!!",
        "!!BNNE!!!!$$$$!!!!!!",
        "))FD@I))))$$$$<?0000",
        "4444444444!$!!!!!!!!",
        "4444444444!$!!!!!!!!",
        "%%%%%%%%(&!$!!!!++++",
        "56565656&(!$!!!!----",
        "++(&;;;;;;!$!!!!!!!!",
        "--&(;;;;;;!$00<?0000",
        "++(&;;;;;;!$!!!!!!!!",
        "--&(;;;;;;!$!!!!!!!!",
        "++(&!!!!!!!!T!!!!!!!",
        "--&(!!$$$$$$$$!!!!!!",
        "++(&!$$$$$$$$!!!!!!!",
        "--&(!$$$$$$$$!!!!!!!",
        "++(&!!$$$$$$$!++!!!!",
        "--&(!!!!!!!!$!--!!!!",
        "++(&%%%%%%!!$!++++!!",
        "--&(%%%%%%!!$!----!!",
        "$$!!!!!!%%!!T!!!!!!!",
        "$$0000<?5600$$<?0000",
        "$$++++!!%%!!$!!!!!!!",
        "$$----!!%%!!$!!!!!!!",
        "$$%%%%%%%%!!$!++++!!",
        "$$%%%=%%%%!!$!----!!",
        "$$(&++++%%!!$!++++!!",
        "$$&(----%%!!$!----!!",
        "$$(&(&(&(&!!T!!!!!!!",
        "$$&(&(&(&($$$$$$$$$$",
        "$$$$$$/&(&$$$$$$$$$$",
        "$$$$$$/&&($$$$$$$$$$",
        nullptr
    },
    {
        // 디그다 동굴 입구 차단 NPC — (12, 9) 워프 자리에 배치해서 진입 차단
        {12, 9, {
            L"연구원: 안쪽은 위험한 디그다가 많아!",
            L"연구원: 지금은 들어갈 수 없어. 다음에 다시 와줘.",
            nullptr
        }, NPC_SPR_GENTLEMAN},

        // 2번도로 아이템볼 1 → 이상한사탕
        {13, 54, {
            L"포켓볼을 주웠다! 안에 이상한사탕이 들어있다!",
            nullptr
        }, NPC_SPR_POKE_BALL, 0, NPC_TAG_ITEMBALL_CANDY},

        // 2번도로 아이템볼 2 → 이상한사탕
        {13, 45, {
            L"포켓볼을 주웠다! 안에 이상한사탕이 들어있다!",
            nullptr
        }, NPC_SPR_POKE_BALL, 0, NPC_TAG_ITEMBALL_CANDY},
    }, 3,  // npcs
    {}, 0,  // trainers
    {
        // 디그다 동굴 입구 (NPC가 차단 중이지만 워프는 유지 — 추후 NPC 제거 시 복구)
        {12, 9, -1  /*DIGLETTS_CAVE_ROUTE_2*/, -1, -1},
        // Forest 북쪽 게이트 입구 (3,11) → MAP_16 위쪽 (5,0)
        {3, 11, MAP_FOREST_NORTH_GATE, 5, 0},
        {15, 19, -1  /*ROUTE_2_TRADE_HOUSE*/, -1, -1},
        // Route 2 Gate 입구 (16,35) → MAP_15 위쪽 (5,0)
        {16, 35, MAP_ROUTE2_GATE, 5, 0},
        // Route 2 Gate 입구 (15,39) → MAP_15 아래쪽 (4,7)
        {15, 39, MAP_ROUTE2_GATE, 4, 7},
        // Forest 남쪽 게이트 입구 (3,43) → MAP_17 아래쪽 (4,7)
        {3, 43, MAP_FOREST_SOUTH_GATE, 4, 7},
    }, 6,  // warps
    {
        {19, 3, 5, 50},
        {16, 3, 5, 50},
    }, 2,  // encounters
    MAP_PEWTER, MAP_VIRIDIAN,  // north/south (pokered: Pewter north, Viridian south)
    10, 35, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Viridian Forest (34×48) ─ pokered ViridianForest.blk (17×24 blocks) ─
inline MapDef MAP_4 = {
    MAP_VIR_FOREST, 34, 48,
    "Viridian Forest", L"상록숲",
    {
        // gen_gate_forest_tiles.py — pokered ViridianForest.blk 원본
        "$!!$%&$$$$$$$$%&$$$$$$$$$$$$$$$$$$",
        "$!+$()!!!!!!!!()!!!!!!!!!!!!!!!!!$",
        "$!!$%&!!!!!!!!%&!!!!!!!!!!!!!!!!!$",
        "$!!$()!!!!!!!*()!!!*$$$$$$$$$$!*!$",
        "$!!$%&!!!$$!!!%&!!!$%&%&%&%&%&$!!$",
        "$!!$()!*!$$!!!()!!!$()()()()()$!!$",
        "$;;$%&;;;$$;;;%&;;;$%&%&%&%&%&$!!$",
        "$;;$();;;$$;;;();;;$()()()()()$!!$",
        "$;;$%&;;;$$;;;%&;;;;;;;;!!!!!!!!!$",
        "$;;$();;;$$;;;();;;;;;;;!!!*!!!!!$",
        "$;;$%&;;;$$;;;%&;;;$%&%&$!!$%&;;;$",
        "$;;$();;;$$;;;();;;$()()$!!$();;;$",
        "$;;$%&;;;$$;;;%&;;;$%&%&$!!$%&;;;$",
        "$;;$();;;$$;;;();;;$()()$!!$();;;$",
        "$;;$%&;;;$$;;;%&;;;$%&%&$!!$%&;;;$",
        "$;;$();;;$$;;;();;;$()()$!!$();;;$",
        "$;;$%&;;;$$;;;!!;;;$%&%&$!!$%&;;;$",
        "$;;$();;;$$;;;!!;;;$()()$!+$();;;$",
        "$;;$%&;;;$$!!!!!!!!$%&%&$!!!!!!!!$",
        "$;;$();;;$$!!*!!!!!$()()$!!*!!!!!$",
        "$;;$%&;;;$%&%&%&%&%&%&%&$;;;%&$!!$",
        "$;;$();;;$()()()()()()()$;;;()$!!$",
        "$;;;!!;;;$%&%&%&%&%&%&%&$;;;%&$!!$",
        "$;;;!!;;;$()()()()()()()$;;;()$!!$",
        "$!!!+!!!!!!!!$%&%&%&%&%&$;;;%&$!!$",
        "$!!!!!!*!!!!!$()()()()()$;;;()$!!$",
        "%&%&%&%&%&$!!$%&%&%&%&%&$;;;%&$!!$",
        "()()()()()$!!$()()()()()$;;;()$!!$",
        "%&%&%&%&%&$!!$%&%&%&%&%&$;;;%&$!!$",
        "()()()()()$!!$()()()()()$;;;()$!!$",
        "$;;;;;;;;$%&%&%&%&%&%&%&$;;;%&$!!$",
        "$;;;;;;;;$()()()()()()()$;;;()$!!$",
        "%&%&%&!!;;;;;;;;+!;$%&%&$;!!!!!!!$",
        "()()()!*;;;;;;;;!!;$()()$;!!!!!*!$",
        "%&%&%&!!;$%&%&$;!!;$%&%&$;!!%&%&%&",
        "()()()!!;$()()$;!!;$()()$;!!()()()",
        "%&%&%&!!;$%&%&$;!!;$%&%&$;!!%&%&%&",
        "()()()!!;$()()$;!!;$()()$;!!()()()",
        "%&%&%&!!;$%&%&$;!!;$%&%&$;!!%&%&%&",
        "()()()!!;$()()$;!!;$()()$;!!()()()",
        "$;;;;;!!;;;;;;;;!!;;;;;;+;!!;;;;;$",
        "$;;;;;!!;;;;;;;;%&;;;;;;;;!!;;;;;$",
        "$;;;;;!!!!!!!!!!()!!!!!!!!!!;;;;;$",
        "$;;;;;!!!!!!!!!!!!!!!!!!!!!!;;;;;$",
        "%&%&%&%&%&%&%&$!!!!$%&%&%&%&%&%&%&",
        "()()()()()()()$!!!+$()()()()()()()",
        "%&%&%&%&%&%&%&$!,-!$%&%&%&%&%&%&%&",
        "()()()()()()()$!!!!$()()()()()()()",
        nullptr
    },
    {
        // 상록숲 일반 NPC
        {16, 43, {
            L"소년: 포켓몬을 잡으러 왔어요!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},

        // 상록숲 일반 NPC 2
        {27, 40, {
            L"소년: 오늘은 꼭 포켓몬을 잡을거야!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},

        // 상록숲 아이템볼 → 이상한사탕
        {25, 11, {
            L"포켓볼을 주웠다! 안에 이상한사탕이 들어있다!",
            nullptr
        }, NPC_SPR_POKE_BALL, 0, NPC_TAG_ITEMBALL_CANDY},

        // 상록숲 아이템볼 → 이상한사탕
        {12, 29, {
            L"포켓볼을 주웠다! 안에 이상한사탕이 들어있다!",
            nullptr
        }, NPC_SPR_POKE_BALL, 0, NPC_TAG_ITEMBALL_CANDY},

        // 상록숲 아이템볼 → 이상한사탕
        {1, 31, {
            L"포켓볼을 주웠다! 안에 이상한사탕이 들어있다!",
            nullptr
        }, NPC_SPR_POKE_BALL, 0, NPC_TAG_ITEMBALL_CANDY},
    }, 5,  // npcs
    {
        // pokered VIRIDIANFOREST_YOUNGSTER2 (30, 33) facing LEFT — BugCatcher #1
        {30, 33, 2, 4,
            L"벌레잡이 소년",
            L"너 포켓몬 트레이너지! 나와 한판 붙자!",
            {13, 10, 0},        // 뿔충이 + 캐터피
            {6, 6, 0},
            false,
            NPC_SPR_BRUNETTE,
            4,
            false
        },

        // pokered VIRIDIANFOREST_YOUNGSTER3 (30, 19) facing LEFT — BugCatcher #2
        {30, 19, 2, 4,
            L"벌레잡이 소년",
            L"이봐! 포켓몬 가지고 있구나! 자, 한판 붙자!",
            {13, 14, 13},       // 뿔충이 + 단데기 + 뿔충이
            {7, 7, 7},
            false,
            NPC_SPR_BRUNETTE,
            4,
            false
        },

        // pokered VIRIDIANFOREST_YOUNGSTER4 (2, 18) facing LEFT — BugCatcher #3
        // 원본은 (30,33) 중복이었으나 (2,18)이 정상 위치
        {2, 18, 2, 4,
            L"벌레잡이 소년",
            L"숲에서 만난 트레이너끼리는 싸우는 게 룰이야!",
            {13, 0, 0},         // 뿔충이 단일
            {9, 0, 0},
            false,
            NPC_SPR_BRUNETTE,
            4,
            false
        },
    }, 3,  // trainers
    {
        // 북쪽 출구 (1,0)(2,0) → North Gate 아래쪽 (4,7)/(5,7) - 둘 다 walkable
        {1, 0, MAP_FOREST_NORTH_GATE, 4, 7},
        {2, 0, MAP_FOREST_NORTH_GATE, 5, 7},
        // 남쪽 출구 (15-18, 47) → South Gate 위쪽 (5,0) [도어 walkable 위치]
        // (4,0)은 pokered 도어 블록의 좌측 데코레이션이라 막힘 — 모두 (5,0)로 통일
        {15, 47, MAP_FOREST_SOUTH_GATE, 5, 0},
        {16, 47, MAP_FOREST_SOUTH_GATE, 5, 0},
        {17, 47, MAP_FOREST_SOUTH_GATE, 5, 0},
        {18, 47, MAP_FOREST_SOUTH_GATE, 5, 0},
    }, 6,  // warps
    {
        {10, 3, 5, 55},
        {13, 3, 5, 35},
        {25, 3, 5, 5},
        {11, 4, 6, 5},
    }, 4,  // encounters
    -1, -1,  // north/south (게이트로만 접근, 스크롤 연결 없음)
    9, 27, 9, 0,  // entry points
    nullptr  // bgm
};

// ─── Pewter City (20×18) ─────────────────────────────────────
inline MapDef MAP_5 = {
    MAP_PEWTER, 40, 36,
    "Pewter City", L"회색시티",
    {
        // gen_overworld_tiles_v3.py 자동 생성
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "!!!!))))))))))))))))))))))))))))))$$$$$$",
        "888h(&++++b222222cJ2222K!!!!!!++++!$$$$$",
        "***1&(----d333333eQ3333U$$$$!!----!$$$$$",
        "***1(&++++w[[[[[[xBNNNNE!!T!!!++++!$$$$$",
        "***1&(----y]]]]]]zFD@@@I!!$$!!----!$$$$$",
        "***1%%!!!!BNNNLpNE%%!!!!!!!$!!!!!!!$$$$$",
        "***156<?00F@@@D:@I56000000<$00<?00<$$$$$",
        "***1(&(&(&(&(&%%(&(&!!!!!!!!!!!!!!!$$$$$",
        "***1&(&(&(&(&(%=&(&(!!!!!!!!!!!!!!!$$$$$",
        "***1(&++++++++++++(&(&(&(&(&(&(&(&i88888",
        "***1&(------------&(&(&(&(&(&(&(&(A*****",
        "***1(&(&(&(&(&(&(&(&!!!!!!!!V>>W(&A*****",
        "***1&(&(&(&(&(&(&(&(!!!!!!!!_D:`&(A*****",
        "***1(&!!!!(&b2222c(&(&J22K(&(&(&(&A*****",
        "***1&(!!!!&(d3333e&(&(Q33U&(&(&(&(j77777",
        "***1(&!!!!%%f^st^S(&!!BNNE!!!!!!(&(&1!!!",
        "***1&(!!!!%=g:::GP&(!!FMRI!!!!!!&(&(1!!!",
        "***1(&(&(&(&(&(&(&/&(&(&(&(&(&(&%%(&1!!!",
        "***1&(&(&(&(&(&(&(/&&(&(&(&(&(&(%=&(1!!!",
        "***1(&!!!!(&!!!!!!/&!!!!!!!!!!!!(&i88888",
        "***1$$$$$$$$$$$$$$/&!!!!!!!!!!!!&(A*****",
        "***1(&(&(&(&J22K(&(&%%%%%%%%%%%%(&A*****",
        "***1&(&(&(&(Q33U&(&(%%///=////%%&(A*****",
        "***1(&!!!!!!BNNE++(&!$++++++++$!(&A*****",
        "***1&(!!!!!!FCOI--&(!$--------$!&(j77777",
        "***1(&(&(&(&(&(&(&(&!$++++++++$!(&!)!!!!",
        "***1&(&(&(&(&(&(&(&(!$--------$!&(!)!!!!",
        "***1(&V>>W++!!!!!!%%!$!!!!!!!!$!(&!)!!!!",
        "*{7a&(_D:`--!!!!!!%=!$00<?0000$!&(!)!!!!",
        "*1))(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&!)!!!!",
        "*1))&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(!)!!!!",
        "*1))))))))))$$$$$$(&$$$$$$))))))))))!!!!",
        "7a!!!!!!!!!!$$$$$$&($$$$$$!!!!!!!!!!!!!!",
        "!!!!!!!!!!!!$$$$$$(&$$$$$$!!!!!!!!!!!!!!",
        "!!!!!!!!!!!!$$$$$$&($$$$$$!!!!!!!!!!!!!!",
        nullptr
    },
    {
        // 동쪽 3번도로 입구 차단 노인 — 게임 스코프 한정용 커스텀 NPC
        // (원본 (35,16)의 YOUNGSTER "브록한테 데려가줄게" 대신 배치)
        {35, 17, {
            L"할아버지: 으흠... 3번도로는 지금 공사중이라네.",
            L"할아버지: 미안하지만 지금은 들어갈 수 없어.",
            L"할아버지: 공사가 끝나면 다시 와주게.",
            nullptr
        }, NPC_SPR_GRAMPS},

        // pokered PEWTERCITY_COOLTRAINER_F (8, 15) — _PewterCityCooltrainerFText
        {8, 15, {
            L"연구생: 소문에 따르면 픽시는 달에서 왔대요!",
            L"연구생: 문스톤이 달의돌산에 떨어진 후 나타났다고 하네요.",
            nullptr
        }, NPC_SPR_BRUNETTE},

        // pokered PEWTERCITY_COOLTRAINER_M (17, 25) — _PewterCityCooltrainerMText
        {17, 25, {
            L"연구생: 여기엔 진지한 포켓몬 트레이너가 별로 없어요.",
            L"연구생: 다들 벌레잡이 같은 풋내기들이죠.",
            L"연구생: 하지만 회색체육관의 브록은 정말 진심이라구요!",
            nullptr
        }, NPC_SPR_BRUNETTE},

        // pokered PEWTERCITY_SUPER_NERD1 (27, 17) — _PewterCitySuperNerd1ItsRightHereText
        {27, 17, {
            L"연구원: 박물관 들러봤어?",
            L"연구원: 바로 여기야! 입장료 내야 하지만 그만한 가치가 있다구!",
            nullptr
        }, NPC_SPR_GENTLEMAN},

        // pokered PEWTERCITY_SUPER_NERD2 (26, 25) — _PewterCitySuperNerd2ImSprayingRepelText
        {26, 25, {
            L"연구원: 쉿! 내가 뭐 하는지 알아?",
            L"연구원: 리펠 뿌려서 정원에 포켓몬 못 오게 하는 거야!",
            nullptr
        }, NPC_SPR_GENTLEMAN},
    }, 5,  // npcs
    {}, 0,  // trainers
    {
        {14, 7, -1  /*MUSEUM_1F*/, -1, -1},
        {19, 5, -1  /*MUSEUM_1F*/, -1, -1},
        {16, 17, MAP_PEWTER_GYM, 4, 12},  // 체육관 정문 안쪽 (도어 (4,13) 한 칸 위)
        {29, 13, -1  /*PEWTER_NIDORAN_HOUSE*/, -1, -1},
        {23, 17, MAP_PEWTER_MART, 3, 7},
        {7, 29, -1  /*PEWTER_SPEECH_HOUSE*/, -1, -1},
        {13, 25, MAP_PEWTER_PC, 3, 7},
    }, 7,  // warps
    {}, 0,  // no encounters
    -1, MAP_ROUTE2,  // north/south (pokered: Pewter는 Route 2와 직접 연결)
    10, 17, -10, 0,  // entry points (south -10: Pewter→Route2 offset)
    nullptr  // bgm
};

// ─── Oak's Lab (10×12) — gym tileset, quadrant별 정밀 layout ─────
// gen_oaklab_tiles.py가 OaksLab.blk + gym.bst를 디코드:
// 14 unique step variant (block의 4 quadrant마다 다른 atomic 4-tuple).
// '+'=floor(walkable), 'D'=도어. 나머지 12 char = 가구 종류별 (모두 unwalkable).
inline MapDef MAP_6 = {
    MAP_OAK_LAB, 10, 12,
    "Oak's Lab", L"오박사 연구소",
    {
        "]]]]``[[[[",   // 윗책장 (왼쪽 책장 윗부분 + 가운데 책장 윗 + 우측 책장 윗)
        "<>=_++||||",   // 책장 본체 (왼쪽 가구 + 통로 + 우측 책장)
        ":-:-++++++",   // 좌측 카운터 + 빈
        "++++++={_+",   // 빈 + 우측 카운터 위 (몬스터볼 자리!)
        "++++++:}-+",   // 빈 + 카운터 앞면
        "++++++++++",
        "[[[[++[[[[",   // 책장 윗부분 + 통로
        "||||++||||",   // 책장 본체 + 통로
        "++++++++++",   // 빈 (블루/NPC 자리)
        "++++++++++",
        "++++++++++",   // 입구 floor
        "++++??++++",   // OakLab 전용 도어 (gym tileset 모양 — 다른 맵 'D'와 분리)
        nullptr
    },
    {
        // 우측 카운터 위 (y=3, x=6,7,8) — 선택한 스타터 볼은 starterIdx로 숨김
        {6, 3, {L"이상해씨의 몬스터볼이다.", L"오박사: 멋대로 만지면 안 돼!", nullptr},
            NPC_SPR_POKE_BALL, 0, NPC_TAG_BALL_BULBASAUR},
        {7, 3, {L"파이리의 몬스터볼이다.",   L"오박사: 멋대로 만지면 안 돼!", nullptr},
            NPC_SPR_POKE_BALL, 0, NPC_TAG_BALL_CHARMANDER},
        {8, 3, {L"꼬부기의 몬스터볼이다.",   L"오박사: 멋대로 만지면 안 돼!", nullptr},
            NPC_SPR_POKE_BALL, 0, NPC_TAG_BALL_SQUIRTLE},
        // 오박사 — partySize==0이면 STARTER_TRIGGER, 이후 소포 퀘스트 처리
        {5, 3, {
            L"오박사: 나에겐 연구에 쓰던 세 마리의 포켓몬이 있단다.",
            L"오박사: 테이블 위 몬스터볼 안에 있어.",
            L"오박사: 자, 어떤 녀석이 마음에 드니?",
            nullptr
        }, NPC_SPR_OAK, 1, NPC_TAG_OAK_LAB},
        // 블루 — beatenRival1 후 대사 변경 → rivalLabTalked 되면 사라짐
        {4, 8, {
            L"블루: 야, 늦었잖아!",
            L"블루: 할아버지, 저도 한 마리 받을게요!",
            nullptr
        }, NPC_SPR_BLUE, 0, NPC_TAG_BLUE_LAB},
        // 보조원 소녀 (왼쪽)
        {1, 9, {
            L"보조원: 안녕하세요!",
            L"보조원: 오박사님은 저쪽에 계세요.",
            nullptr
        }, NPC_SPR_GIRL},
        // 과학자 (오른쪽)
        {8, 9, {
            L"과학자: 포켓몬 연구는 정말 재밌어요!",
            nullptr
        }, NPC_SPR_GENTLEMAN},
    }, 7,  // npcs
    {}, 0,  // trainers
    {
        // 도어 → 팔레트시티 (12,12) 연구소 정문 바로 아래 floor.
        // -1,-1 (southEntry 사용)면 팔레트 (10,0) = 풀숲 진입점에 떨어져 OAK_INTERCEPT 재발동됨.
        {4, 11, MAP_PALLET, 12, 12},
        {5, 11, MAP_PALLET, 12, 12},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 'D'/'?' 워프만 사용)
    5, 11, 5, 10,  // entry: 정문(12,11→연구소) 진입 시 (5,10) 문 안쪽
    nullptr  // bgm
};

// ─── Player's House (8×8) ─────────────────────────────────────
inline MapDef MAP_7 = {
    MAP_PLAYER_HOUSE, 8, 8,
    "Player's House", L"주인공의 집",
    {
        "qqrsrsrs",
        "ttuvuuuw",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuxyzxuu",
        "uuxABxuu",
        "uuuuuuuu",
        "uuCCuuuu",   // (2,7)(3,7) = 'C' 카펫 도어매 (pokered RedsHouse1F block 0x0B BL/BR)
        nullptr
    },
    {
        // Mom NPC at (5,4) — pokered 원본 위치 (RedsHouse1F.asm)
        {5, 4, {
            L"엄마: 그래. 남자애는 언젠가 집을 떠난다지.",
            L"엄마: TV에서 그러더라.",
            L"엄마: 옆집의 오박사님이 너를 찾고 계셔.",
            nullptr
        }},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        // 정문 카펫 (2,7)(3,7) = 'C' → 팔레트시티 (5,6) — 플레이어 집(5,5) 바로 아래
        {2, 7, MAP_PALLET, 5, 6},
        {3, 7, MAP_PALLET, 5, 6},
        // 사다리 'w' (7,1) → 2F (7,2)
        {7, 1, MAP_PLAYER_HOUSE2, 7, 2},
    }, 3,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 'C' 워프만 사용)
    3, 7, 3, 7,  // entry: 팔레트→1F 도착시 (3,7) (정문)
    nullptr  // bgm
};

// ─── Player's Bedroom 2F (12×10) ─────────────────────────────────
// 사방에 벽(#), 좌측 상단 침대(bb), 컴퓨터(p), TV(s), 우측 상단 계단(D).
inline MapDef MAP_9 = {
    MAP_PLAYER_HOUSE2, 8, 8,
    "Player's Bedroom", L"주인공의 방",
    {
        "abcddede",
        "fghiiiij",
        "iiiiiiii",   // pokered RedsHouse2F block (2,1)=0x0F floor 동질 — ##(grass) → ii(floor)
        "iiiiiiii",
        "iiikiiii",
        "iiiliiii",
        "miiiiini",
        "oiiiiipi",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        // 사다리 'j' (7,1) → 1F (7,2). 사다리 밟으면 즉시 워프
        {7, 1, MAP_PLAYER_HOUSE, 7, 2},
    }, 1,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 벽 fall-through 없음 (사다리 'j' 만 1F로 이동)
    7, 2, 7, 2,  // entry: 1F→2F 도착시 (7,2) (사다리 한 칸 아래)
    nullptr  // bgm
};

// ─── Pewter Gym (10×14) ─── pokered PewterGym.blk (5×7 blocks)
// pokered 원본 NPC 3명 매핑 (data/maps/objects/PewterGym.asm):
//   (4,1) BROCK 보스 (DOWN, OPP_BROCK) — 꼬마돌12 + 롱스톤14, 승리 → 회색뱃지/엔딩
//   (3,6) Jr Trainer (RIGHT, OPP_JR_TRAINER_M) — 잡몹, 시야 5칸
//   (7,10) GYM_GUIDE — 비전투, 트레이너 팁 NPC
// 출구 도어 (4,13)(5,13) → Pewter (16,17)
inline MapDef MAP_8 = {
    MAP_PEWTER_GYM, 10, 14,
    "Pewter Gym", L"회색시티 체육관",
    {
        // gen_pewter_gym_tiles.py — pokered PewterGym.blk
        "$$$$$$$$$$",
        "$!!!!!!!!$",
        "$!!!!!!!!$",
        "$$$$!!$$$$",
        "$!!!!!!!!$",
        "$!$!!$$$!$",
        "$!!!!!!!!$",
        "$!$!!$$$!$",
        "$!!!!!!!!$",
        "$$$%!!%$$$",
        "!!!&!!&!!!",
        "!!!!!!!!!!",
        "!!!!!!!!!!",
        "!!!!?\?!!!!",  // ?\?: 트라이그래프 회피 (??! → |)
        nullptr
    },
    {
        // GYM_GUIDE (7,10) — pokered _PewterGymGuidePreAdviceText 요약본
        {7, 10, {
            L"안내인: 어이! 너 챔피언이 될 자질이 보이는걸!",
            L"안내인: 나는 트레이너는 아니지만 한 수 알려줄게.",
            L"안내인: 앞쪽 포켓몬이 먼저 나가니까 순서를 잘 정해!",
            nullptr
        }, NPC_SPR_GENTLEMAN},
    }, 1,  // npcs
    {
        // Jr Trainer (3,6) facing RIGHT, sightRange 5 — pokered _PewterGymCooltrainerMBattleText
        // 원본 파티: Diglett(50) + Sandshrew(27) Lv11 — 두 종 모두 미구현이라 꼬마돌+꼬렛으로 대체
        {3, 6, /*dir=RIGHT*/3, /*sight*/5,
            L"주니어 트레이너",
            L"거기서! 너 같은 풋내기가 브록 님 앞에 갈 수준은 아니야!",
            {74, 19, 0},   // 꼬마돌, 꼬렛
            {11, 11, 0},
            false,
            NPC_SPR_COOLTRAINER_M,  // OW: 주니어 트레이너
            5,                      // intro: COOLTRAINER_M
            false                   // isBoss
        },
        // BROCK (4,1) facing DOWN, sightRange 10 — 보스. 파티는 startBrock()에서 하드코딩(꼬마돌12+롱스톤14).
        // pokered _PewterGymBrockPreBattleText 요약. 승리 시 player_.beatenBrock=true → ENDING.
        {4, 1, /*dir=DOWN*/0, /*sight*/10,
            L"관장 브록",
            L"나는 회색시티 체육관의 관장 브록!\n바위 포켓몬은 최강이다!",
            {74, 95, 0},   // 꼬마돌, 롱스톤 (참고용 — startBrock이 덮어씀)
            {12, 14, 0},
            false,
            NPC_SPR_SUPER_NERD,     // OW: 체육관 관장(브록)
            3,                      // intro: BROCK
            true                // isBoss → BOSS_BATTLE
        },
    }, 2,  // trainers
    {
        // 출구 (4,13)(5,13) → Pewter (16,17) 체육관 앞
        {4, 13, MAP_PEWTER, 16, 17},
        {5, 13, MAP_PEWTER, 16, 17},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 '?' 워프만 사용)
    4, 13, 4, 0,  // entry points
    nullptr  // bgm
};

// ─── Rival's House (8×8) ─────────────────────────────────────
// pokered BluesHouse 원본 — single floor (2층 없음). Daisy(블루의 누나) NPC + 책장.
// 정문 (2,7)(3,7) → 팔레트시티 (13,6).
// (7,1)은 player house 1F의 사다리 'w' 자리였으나 라이벌 집은 2층 없으므로 'q' 벽으로 변경.
inline MapDef MAP_10 = {
    MAP_RIVAL_HOUSE, 8, 8,
    "Rival's House", L"라이벌의 집",
    {
        "qqrsrsrs",
        "ttuvuuuv",   // 원작 BluesHouse (3,0) block 0x09 = 책장 → step (7,1) = 'v' (책상/책장)
        "uuuuuuuu",
        "uuxyzxuu",
        "uuxABxuu",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuCCuuuu",   // (2,7)(3,7) = 'C' 카펫 (pokered BluesHouse block 0x0B BL/BR)
        nullptr
    },
    {
        // Daisy (블루의 누나) — 책상 옆 (3,3)
        {3, 3, {
            L"데이지: 안녕! 동생은 할아버지 연구소에 갔단다.",
            L"데이지: 너도 곧 모험을 떠나는 거지?",
            L"데이지: 포켓몬은 살아있는 친구야. 잘 돌봐줘!",
            nullptr
        }, NPC_SPR_BRUNETTE},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        {2, 7, MAP_PALLET, 13, 6},
        {3, 7, MAP_PALLET, 13, 6},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 'C' 워프만 사용)
    3, 7, 3, 7,
    nullptr
};


// ─── ViridianPokecenter (14×8) — pokered 원본 디코딩 ─────
inline MapDef MAP_11 = {
    MAP_VIRIDIAN_PC, 14, 8,
    "Pokemon Center", L"포켓몬센터",
    {
        // gen_pokecenter_mart_tiles.py
        "*23:;*23))4)4)",
        "*5<$!*5=!!!!!!",
        "6>%?%6%%%%7!7%",
        "!!!!!!!!!!!!!@",
        "AB!!!!!!!!!!!C",
        "D$!!!!!!!!!!!!",
        "&&!!!!&&!!!!&&",
        "((!++!((!!!!((",
        nullptr
    },
    {
        // 간호사 조이 — 카운터 뒤 (3,1) — 대화 끝 → NURSE_HEAL
        {3, 1, {
            L"간호사 조이: 어서오세요!",
            L"간호사 조이: 포켓몬을 치료해드리겠습니다... 잠시만요.",
            L"완료! 포켓몬들이 모두 회복됐습니다!",
            nullptr
        }, NPC_SPR_NURSE, 2},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        // 출구 워프: 입구 도어 위치 (대략 가운데 하단)
        {3, 7, MAP_VIRIDIAN, 23, 26},
        {4, 7, MAP_VIRIDIAN, 23, 26},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    3, 7, 3, 7,  // entry: 도착시 (3,7)
    nullptr  // bgm
};


// ─── PewterPokecenter (14×8) — pokered 원본 디코딩 ─────
inline MapDef MAP_12 = {
    MAP_PEWTER_PC, 14, 8,
    "Pokemon Center", L"포켓몬센터",
    {
        // gen_pokecenter_mart_tiles.py
        "*23:;*23))4)4)",
        "*5<$!*5=!!!!!!",
        "6>%?%6%%%%7!7%",
        "!!!!!!!!!!!!!@",
        "AB!!!!!!!!!!!C",
        "D$!!!!!!!!!!!!",
        "&&!!!!&&!!!!&&",
        "((!++!((!!!!((",
        nullptr
    },
    {
        // 간호사 조이 — 카운터 뒤 (3,1) — 대화 끝 → NURSE_HEAL
        {3, 1, {
            L"간호사 조이: 어서오세요!",
            L"간호사 조이: 포켓몬을 치료해드리겠습니다... 잠시만요.",
            L"완료! 포켓몬들이 모두 회복됐습니다!",
            nullptr
        }, NPC_SPR_NURSE, 2},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        // 출구 워프: 입구 도어 위치 (대략 가운데 하단)
        {3, 7, MAP_PEWTER, 13, 26},
        {4, 7, MAP_PEWTER, 13, 26},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    3, 7, 3, 7,  // entry: 도착시 (3,7)
    nullptr  // bgm
};


// ─── ViridianMart (8×8) — pokered 원본 ─────
inline MapDef MAP_13 = {
    MAP_VIRIDIAN_MART, 8, 8,
    "ViridianMart", L"프렌들리숍",
    {
        // gen_pokecenter_mart_tiles.py
        ",,----,,",
        "..////..",
        "$!!!!!!!",
        "01!!0101",
        ")E$!8989",
        "$F$!!!!!",
        "GH$!!!!!",
        "$!!++!!!",
        nullptr
    },
    {
        // 점원 — 카운터 (0,5) facing RIGHT — pokered ViridianMart_Object.asm
        // trigger=3 → 대화 끝 시 deliveredParcel=true (별도 씬 X)
        {0, 5, {
            L"점원: 어서오세요! 오, 너 혹시 오박사님 심부름 왔니?",
            L"점원: 잠시만, 여기 소포가 있단다.",
            L"[소포를 받았다!]  오박사님께 전해드려.",
            nullptr
        }, NPC_SPR_CLERK, 3, NPC_TAG_VIRIDIAN_CLERK, 1 /* MART_VIRIDIAN */},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        {3, 7, MAP_VIRIDIAN, 29, 20},
        {4, 7, MAP_VIRIDIAN, 29, 20},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    3, 7, 3, 7,  // entry
    nullptr  // bgm
};


// ─── PewterMart (8×8) — pokered 원본 ─────
inline MapDef MAP_14 = {
    MAP_PEWTER_MART, 8, 8,
    "PewterMart", L"프렌들리숍",
    {
        // gen_pokecenter_mart_tiles.py
        ",,----,,",
        "..////..",
        "$!!!!!!!",
        "01!!0101",
        ")E$!8989",
        "$F$!!!!!",
        "GH$!!!!!",
        "$!!++!!!",
        nullptr
    },
    {
        // 점원 — 카운터 (0,5) facing RIGHT — pokered PewterMart 위치
        {0, 5, {
            L"점원: 어서오세요!",
            L"점원: 프렌들리숍에 오신 것을 환영합니다.",
            L"점원: 무엇을 도와드릴까요?",
            nullptr
        }, NPC_SPR_CLERK, 0, 0, 2 /* MART_PEWTER */},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        {3, 7, MAP_PEWTER, 23, 18},
        {4, 7, MAP_PEWTER, 23, 18},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    3, 7, 3, 7,  // entry
    nullptr  // bgm
};


// ─── Route2Gate (10×8) — pokered 원본 ─────
// Route 2 중간을 가르는 게이트 건물. (4,0)→Route2 (16,35), (5,0)→Route2 (16,35),
// (4,7)→Route2 (15,39), (5,7)→Route2 (15,39). 같은 Route 2 맵 안의 두 구역을 연결.
inline MapDef MAP_15 = {
    MAP_ROUTE2_GATE, 10, 8,
    "Route 2 Gate", L"2번도로 게이트",
    {
        // gen_gate_forest_tiles.py
        "$$$$$+$$$$",
        "!!!!!!!!!!",
        "%!!!!!(!(%",
        "&!!!!!)!)&",
        "%!!!!!!!!%",
        "&!!!!!(!(&",
        "%!!!!!)!)%",
        "&!!!**!!!&",
        nullptr
    },
    {
        // pokered ROUTE2GATE_OAKS_AIDE (1, 4) — SCIENTIST, FLASH HM 설명
        {1, 4, {
            L"오박사 보조원: 비전머신 플래시는",
            L"오박사 보조원: 가장 어두운 던전도 환하게 밝혀줍니다.",
            nullptr
        }, NPC_SPR_GENTLEMAN},

        // pokered ROUTE2GATE_YOUNGSTER (5, 4) — Rock Tunnel/FLASH 안내
        {5, 4, {
            L"소년: 포켓몬한테 플래시를 가르치면",
            L"소년: 돌산터널을 통과할 수 있어!",
            nullptr
        }, NPC_SPR_LITTLE_BOY},
    }, 2,  // npcs
    {}, 0,  // trainers
    {
        // 위 출구 (4,0)(5,0) → Route 2 (16,35) [게이트 북쪽 입구의 도착지]
        {4, 0, MAP_ROUTE2, 16, 35},
        {5, 0, MAP_ROUTE2, 16, 35},
        // 아래 출구 (4,7)(5,7) → Route 2 (15,39) [게이트 남쪽 입구의 도착지]
        {4, 7, MAP_ROUTE2, 15, 39},
        {5, 7, MAP_ROUTE2, 15, 39},
    }, 4,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    4, 7, 4, 7,  // entry
    nullptr  // bgm
};

// ─── Viridian Forest North Gate (10×8) — pokered ─────
// Route 2 ↔ Viridian Forest 북쪽 입구를 연결.
// 위쪽 (4,0)(5,0) → Route 2 (3,11). 아래쪽 (4,7)(5,7) → Forest 북쪽 입구 (1,0)/(2,0).
inline MapDef MAP_16 = {
    MAP_FOREST_NORTH_GATE, 10, 8,
    "Forest North Gate", L"상록숲 북쪽 게이트",
    {
        // gen_gate_forest_tiles.py와 동일 (블록 데이터 일치)
        "$$$$$+$$$$",
        "!!!!!!!!!!",
        "%!!!!!(!(%",
        "&!!!!!)!)&",
        "%!!!!!!!!%",
        "&!!!!!(!(&",
        "%!!!!!)!)%",
        "&!!!**!!!&",
        nullptr
    },
    {
        // pokered VIRIDIANFORESTNORTHGATE_SUPER_NERD (3, 2) — 포켓몬 다양성 팁
        {3, 2, {
            L"연구원: 많은 포켓몬은 숲이나 동굴에만 산다구!",
            L"연구원: 여기저기 다녀봐야 다양한 종류를 만날 수 있어!",
            nullptr
        }, NPC_SPR_GENTLEMAN},

        // pokered VIRIDIANFORESTNORTHGATE_GRAMPS (2, 5) — CUT 기술 힌트
        {2, 5, {
            L"할아버지: 길가의 덤불을 봤니?",
            L"할아버지: 특별한 포켓몬 기술로 베어낼 수 있단다.",
            nullptr
        }, NPC_SPR_GRAMPS},
    }, 2,  // npcs
    {}, 0,  // trainers
    {
        // 위 (4,0)(5,0) → Route 2 (3,11) — 게이트 위쪽 입구 위치
        {4, 0, MAP_ROUTE2, 3, 11},
        {5, 0, MAP_ROUTE2, 3, 11},
        // 아래 (4,7)(5,7) → Forest 북쪽 입구 (1,0)/(2,0)
        {4, 7, MAP_VIR_FOREST, 1, 0},
        {5, 7, MAP_VIR_FOREST, 2, 0},
    }, 4,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    4, 7, 4, 7,  // entry
    nullptr  // bgm
};

// ─── Viridian Forest South Gate (10×8) — pokered ─────
// Viridian Forest 남쪽 ↔ Route 2 (3,43) 연결.
// 위쪽 (4,0)(5,0) → Forest 남쪽 (15-18, 47). 아래쪽 (4,7)(5,7) → Route 2 (3,43).
inline MapDef MAP_17 = {
    MAP_FOREST_SOUTH_GATE, 10, 8,
    "Forest South Gate", L"상록숲 남쪽 게이트",
    {
        "$$$$$+$$$$",
        "!!!!!!!!!!",
        "%!!!!!(!(%",
        "&!!!!!)!)&",
        "%!!!!!!!!%",
        "&!!!!!(!(&",
        "%!!!!!)!)%",
        "&!!!**!!!&",
        nullptr
    },
    {
        // pokered VIRIDIANFORESTSOUTHGATE_GIRL (8, 4) — 숲 미로 경고
        {8, 4, {
            L"안내인: 상록숲 가는 거니?",
            L"안내인: 자연이 만든 미로니까 조심해야 해!",
            nullptr
        }, NPC_SPR_GIRL},

        // pokered VIRIDIANFORESTSOUTHGATE_LITTLE_GIRL (2, 4) — 꼬렛 잡았어?
        {2, 4, {
            L"소녀: 꼬렛은 작지만 물면 정말 아파!",
            L"소녀: 너 한 마리 잡았어?",
            nullptr
        }, NPC_SPR_LITTLE_GIRL},
    }, 2,  // npcs
    {}, 0,  // trainers
    {
        // 위 (4,0)(5,0) → Forest 남쪽 (15,47)/(16,47)
        {4, 0, MAP_VIR_FOREST, 15, 47},
        {5, 0, MAP_VIR_FOREST, 16, 47},
        // 아래 (4,7)(5,7) → Route 2 (3,43)
        {4, 7, MAP_ROUTE2, 3, 43},
        {5, 7, MAP_ROUTE2, 3, 43},
    }, 4,  // warps
    {}, 0,  // no encounters
    -1, -1,  // north/south
    4, 7, 4, 7,  // entry
    nullptr  // bgm
};

// ─── Viridian School House (8×8) — pokered ViridianSchoolHouse ─────
// 원본 NPC 2명: (3,5) BRUNETTE_GIRL 노트 외우기, (4,1) COOLTRAINER_F 칠판 안내.
// 워프 (2,7)(3,7) → 상록시티 (21,16) [도어 (21,15) 한 칸 아래].
inline MapDef MAP_18 = {
    MAP_VIRIDIAN_SCHOOL_HOUSE, 8, 8,
    "Viridian School", L"상록시티 학교",
    {
        // 표준 RedsHouse 톤 (벽/floor 패턴 일관). 칠판/책상은 가구 'x','y','z','A','B'로 표현.
        "qqrsrsrs",   // 윗벽 — 칠판은 (4,1)의 COOLTRAINER 위에 있다고 가정
        "ttuuuuuu",   // floor — (4,1) COOLTRAINER 위치
        "uuuuuuuu",
        "uuxyzxuu",   // 책상 줄
        "uuxABxuu",   // 책상 줄
        "uuuuuuuu",   // (3,5) BRUNETTE_GIRL 위치 (책상 옆 floor)
        "uuuuuuuu",
        "uuCCuuuu",   // 도어 (워프 트리거)
        nullptr
    },
    {
        // COOLTRAINER_F (4,1) — pokered: SPRITE_COOLTRAINER_F facing DOWN
        {4, 1, {
            L"연구원: 좋아요!",
            L"연구원: 칠판을 잘 읽어보세요!",
            nullptr
        }, NPC_SPR_BRUNETTE},
        // BRUNETTE_GIRL (3,5) — pokered: SPRITE_BRUNETTE_GIRL facing UP
        {3, 5, {
            L"연구생: 휴~ 노트를 다 외우려고 노력 중이야.",
            nullptr
        }, NPC_SPR_BRUNETTE},
    }, 2,  // npcs
    {}, 0,  // trainers
    {
        // 도어 (2,7)(3,7) → 상록시티 (21,16) — 학교 정문(21,15) 바로 아래 floor
        {2, 7, MAP_VIRIDIAN, 21, 16},
        {3, 7, MAP_VIRIDIAN, 21, 16},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 'C' 워프만 사용)
    3, 7, 3, 7,  // entry
    nullptr  // bgm
};

// ─── Viridian Nickname House (8×8) — pokered ViridianNicknameHouse ─────
// 원본 NPC 4: BALDING_GUY, LITTLE_GIRL, SPEAROW(BIRD), CLIPBOARD 표지판.
// 클론 단순화: 깨비참 케이지를 가구 타일('v')로 표현하고, 표지판 텍스트는 깨비참 인터랙트에 통합.
// 워프 (2,7)(3,7) → 상록시티 (21,10).
inline MapDef MAP_19 = {
    MAP_VIRIDIAN_NICKNAME_HOUSE, 8, 8,
    "Nickname House", L"별명짓기집",
    {
        "qqrsrsrs",
        "ttuvuuuv",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuuuuvuu",   // (5,5) 'v' = 책장/가구 타일 = 깨비참 케이지 비주얼
        "uuuuuuuu",
        "uuCCuuuu",
        nullptr
    },
    {
        // BALDING_GUY (5,3) — pokered: SPRITE_BALDING_GUY (대머리 아저씨)
        {5, 3, {
            L"아저씨: 별명 짓는 건 재밌지만, 어렵단다.",
            L"아저씨: 단순한 이름이 기억하기 가장 쉽지.",
            nullptr
        }, NPC_SPR_GENTLEMAN},
        // LITTLE_GIRL (1,4) — pokered: SPRITE_LITTLE_GIRL
        {1, 4, {
            L"소녀: 우리 아빠도 포켓몬을 좋아하셔!",
            nullptr
        }, NPC_SPR_LITTLE_GIRL},
        // SPEAROW + CLIPBOARD 통합: 케이지 'v' 옆 (4,5) floor 에서 인터랙트
        // POKE_BALL 두 개가 어색해서 클립보드는 제거, 정보는 깨비참 대사로 합침
        {4, 5, {
            L"[케이지 안에서 작은 새가 지저귄다]",
            L"스피어 (깨비참): 츳위~!",
            L"※ 별명: 스피어",
            nullptr
        }, NPC_SPR_POKE_BALL},
    }, 3,  // npcs
    {}, 0,  // trainers
    {
        // 도어 (2,7)(3,7) → 상록시티 (21,10) — 별명집 정문(21,9) 바로 아래
        {2, 7, MAP_VIRIDIAN, 21, 10},
        {3, 7, MAP_VIRIDIAN, 21, 10},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, -1,  // 실내 — 남쪽 경계 fall-through 없음 (도어 'C' 워프만 사용)
    3, 7, 3, 7,  // entry
    nullptr  // bgm
};

// ─── 전체 맵 배열 ────────────────────────────────────────────
// ALL_MAPS의 인덱스 = MAP_xxx 상수값.
// (MAP_PLAYER_HOUSE=7, MAP_PEWTER_GYM=8, MAP_PLAYER_HOUSE2=9, MAP_RIVAL_HOUSE=10)
inline MapDef* ALL_MAPS[] = {
    &MAP_0,
    &MAP_1,
    &MAP_2,
    &MAP_3,
    &MAP_4,
    &MAP_5,
    &MAP_6,
    &MAP_7,
    &MAP_8,
    &MAP_9,
    &MAP_10,
    &MAP_11,
    &MAP_12,
    &MAP_13,
    &MAP_14,
    &MAP_15,
    &MAP_16,
    &MAP_17,
    &MAP_18,
    &MAP_19,
};
inline constexpr int NUM_MAPS = 20;

inline MapDef* getMap(int id) {
    if (id >= 0 && id < NUM_MAPS) return ALL_MAPS[id];
    return nullptr;
}

// ─── 표지판 (Signs) ───────────────────────────────────────────
// 플레이어가 표지판 칸을 마주보고 A 누르면 내용을 보여줌.
// pokered bg_event 와 동일 위치 (또는 비슷한 위치)에 배치.
struct SignDef {
    int mapId;
    int x, y;
    const wchar_t* lines[4];  // 최대 3줄 + nullptr
};

static const SignDef ALL_SIGNS[] = {
    // ─── 팔레트시티 (MAP_0) — '=' 표지판 타일 4개 ───────────────
    {MAP_PALLET, 3, 5, {
        L"주인공의 집",
        nullptr
    }},
    {MAP_PALLET, 11, 5, {
        L"라이벌의 집",
        nullptr
    }},
    {MAP_PALLET, 7, 9, {
        L"오박사 포켓몬 연구소",
        nullptr
    }},
    {MAP_PALLET, 13, 13, {
        L"팔레트시티",
        L"\"영원한 푸르름의 마을\"",
        nullptr
    }},

    // ─── 1번도로 (MAP_1) — '=' 1개 ──────────────────────────────
    {MAP_ROUTE1, 9, 27, {
        L"1번도로",
        L"북쪽 → 상록시티",
        nullptr
    }},

    // ─── 상록시티 (MAP_2) — 'S/R/O/=' 표지판 7개 ────────────────
    {MAP_VIRIDIAN, 19, 1, {
        L"북쪽 → 2번도로 / 회색시티",
        nullptr
    }},
    {MAP_VIRIDIAN, 33, 6, {
        L"상록시티 체육관",
        L"관장이 부재중입니다.",
        nullptr
    }},
    {MAP_VIRIDIAN, 27, 7, {
        L"상록시티",
        L"\"영원한 매혹의 마을\"",
        nullptr
    }},
    {MAP_VIRIDIAN, 17, 17, {
        L"← 22번도로 (공사중)",
        nullptr
    }},
    {MAP_VIRIDIAN, 30, 19, {
        L"포켓몬마트",
        L"포켓몬 도구 판매",
        nullptr
    }},
    {MAP_VIRIDIAN, 24, 25, {
        L"포켓몬센터",
        L"포켓몬을 회복시켜드립니다",
        nullptr
    }},
    {MAP_VIRIDIAN, 21, 29, {
        L"남쪽 → 1번도로 / 팔레트시티",
        nullptr
    }},

    // ─── 2번도로 (MAP_3) — '=' 2개 ──────────────────────────────
    {MAP_ROUTE2, 11, 11, {
        L"2번도로 (북쪽)",
        L"북쪽 → 회색시티",
        nullptr
    }},
    {MAP_ROUTE2, 5, 65, {
        L"2번도로 (남쪽)",
        L"남쪽 → 상록시티",
        nullptr
    }},

    // ─── 상록숲 (MAP_4) — '+' 표지판 타일 6개 ───────────────────
    {MAP_VIR_FOREST, 2, 1, {
        L"← 상록숲 출구 (북쪽 게이트)",
        L"회색시티 방향",
        nullptr
    }},
    {MAP_VIR_FOREST, 26, 17, {
        L"트레이너 팁:",
        L"여기저기 둘러봐야 다양한 포켓몬을",
        L"만날 수 있어요!",
        nullptr
    }},
    {MAP_VIR_FOREST, 4, 24, {
        L"트레이너 팁:",
        L"풀숲에서는 야생 포켓몬이 나옵니다.",
        nullptr
    }},
    {MAP_VIR_FOREST, 16, 32, {
        L"독에 걸렸을 땐 안티독트!",
        L"포켓몬마트에서 구입 가능.",
        nullptr
    }},
    {MAP_VIR_FOREST, 24, 40, {
        L"트레이너 팁:",
        L"숲은 자연이 만든 미로입니다.",
        nullptr
    }},
    {MAP_VIR_FOREST, 18, 45, {
        L"← 상록숲 출구 (남쪽 게이트)",
        L"2번도로 방향",
        nullptr
    }},

    // ─── 회색시티 (MAP_5) — 'S/R/O/=' 표지판 8개 ────────────────
    {MAP_PEWTER, 15, 9, {
        L"회색시티 과학박물관",
        L"고대 포켓몬의 화석을 전시 중.",
        nullptr
    }},
    {MAP_PEWTER, 17, 16, {
        L"회색시티 체육관",
        L"관장: 브록 — 바위 포켓몬 전문",
        nullptr
    }},
    {MAP_PEWTER, 11, 17, {
        L"회색시티",
        L"\"돌과 함께 사는 마을\"",
        nullptr
    }},
    {MAP_PEWTER, 24, 17, {
        L"포켓몬마트",
        L"포켓몬 도구 판매",
        nullptr
    }},
    {MAP_PEWTER, 33, 19, {
        L"3번도로 → (공사중)",
        nullptr
    }},
    {MAP_PEWTER, 25, 23, {
        L"회색시티 안내판",
        L"남쪽으로 가면 상록숲입니다.",
        nullptr
    }},
    {MAP_PEWTER, 14, 25, {
        L"포켓몬센터",
        L"포켓몬을 회복시켜드립니다",
        nullptr
    }},
    {MAP_PEWTER, 19, 29, {
        L"남쪽 → 2번도로 / 상록시티",
        nullptr
    }},
};
static const int NUM_SIGNS = sizeof(ALL_SIGNS) / sizeof(ALL_SIGNS[0]);

inline const SignDef* findSign(int mapId, int x, int y) {
    for (int i = 0; i < NUM_SIGNS; i++) {
        if (ALL_SIGNS[i].mapId == mapId &&
            ALL_SIGNS[i].x == x && ALL_SIGNS[i].y == y) {
            return &ALL_SIGNS[i];
        }
    }
    return nullptr;
}

// walkable: pokered Overworld_Coll 통과 atom(BL)을 가진 char만.
// 분류 근거: 각 char의 atom 4-tuple BL이 OVERWORLD_PASS={00,10,1b,20,21,23,2c,2d,2e,30,31,33,39,3c,3e,52,54,58,5b}에 속하는지.
// PT('!','$','%','(','1','@','H','J','K','^')는 BL=0x4e/0x32/0x14/0x1a/0x3a 등이라 모두 BLOCK.
// map-aware: 각 tileset의 char 의미가 달라서 mapId 로 dispatch
inline bool tileWalkable(char t, int mapId = 0) {
    // Viridian Forest (MAP_4) — forest tileset
    if (mapId == 4) {
        return t == ' ' || t == '!' || t == '*' || t == ',' || t == '-' || t == ';';
    }
    // 오버월드 도시/도로 (MAP_0,1,2,3,5) — v3 atom-based
    // pokered 충돌 분석:
    //   '<' [44,44,55,52]  BL=55=ledge atom → 남쪽 jump-down 절벽 (걷기 불가, isLedge에서 처리)
    //   '?' [44,44,60,60]  BL=60=passable → 일반 walkable 계단
    if (mapId >= 0 && mapId <= 5) {
        return t == ' ' || t == '!' || t == '%' || t == '&' || t == '(' ||
               t == '+' || t == '-' || t == '4' || t == ';' || t == '?' ||
               t == 'C' || t == 'D' || t == 'G' || t == 'M';
    }
    // PC + Mart (MAP_11..14) — pokecenter tileset
    if (mapId >= 11 && mapId <= 14) {
        return t == ' ' || t == '!' || t == '$' || t == '+' || t == '4' || t == 'B';
    }
    // Gate maps (MAP_15 Route2Gate, MAP_16 ForestNorthGate, MAP_17 ForestSouthGate) — gate tileset
    if (mapId == 15 || mapId == 16 || mapId == 17) {
        return t == ' ' || t == '!' || t == '*' || t == '+';
    }
    // Pewter Gym (MAP_8) — gym tileset (gen_pewter_gym_tiles.py)
    if (mapId == 8) {
        return t == '!' || t == '(' || t == '?';
    }
    // 실내 (reds_house, oaklab — MAP_6,7,9,10)
    return t == ' ' || t == 'f' || t == 'i' || t == 'u' || t == '+';
}
inline bool tileIsEncounter(char t) {
    return t == ';';
}
inline char getTile(const MapDef* m, int x, int y) {
    if (!m || x < 0 || x >= m->mapW || y < 0 || y >= m->mapH) return '#';
    if (!m->tiles[y]) return '#';
    int len = 0; while (m->tiles[y][len]) len++;
    if (x >= len) return ' ';
    return m->tiles[y][x];
}

inline bool tileIsDoor(char t) {
    return t == '!' || t == '#' || t == '(' || t == '1' || t == '@' || t == 'A' || t == 'B' || t == 'H' || t == 'I' || t == 'J' || t == 'K' || t == '^' || t == 'w';
}
